### ISSUE TITLE
Префиксы захардкоженны

### ISSUE THREAD

**Issue by Roni-sl** [realpack/some_adminmode#1]
https://github.com/realpack/some_adminmode/blob/6b24382abe4e912f9caa01d75346debf11a1e29a/lua/simple_admin/core/sv_commands.lua#L1

https://github.com/realpack/some_adminmode/blob/6b24382abe4e912f9caa01d75346debf11a1e29a/lua/simple_admin/core/sv_commands.lua#L81

Думаю было бы логично указать префиксы в конфиге и брать уже значения оттуда

**Comment by realpack** [comment]
`nagated_symbol` - врятле уйдет от туда, не думаю что кому-то понадобится изменять его`
`prefix` - В скором времени.

**Comment by AMD-NICK** [comment]
никто не станет изменять префикс, я думаю. Не стоит его в конфиг пихать

**Comment by realpack** [comment]
> никто не станет изменять префикс, я думаю. Не стоит его в конфиг пихать

Суть этой админки это большая гибкость, во всяком случае я так предпологал когда затеял это. Так что я думаю это будет хорошей идеей. 
Если не пригодится, то и не пригодится.

**Comment by AMD-NICK** [comment]
с гибкостью можно переборщить и получить неподдерживаемый продукт

**Comment by realpack** [comment]
> с гибкостью можно переборщить и получить неподдерживаемый продукт
> https://t.me/uFeed/30

Да, я согласен с тобой.
Но я считаю что это может пригодится. Иногда приходилось иметь дело с людьми которые хотели бы увидеть это в админке. Но с другой точке зрения это всего лишь 2-3 человека.
